# Generated by Django 2.2.9 on 2020-04-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300)),
                ('datanasc', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['id'],
                'unique_together': {('email',)},
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300)),
                ('datanasc', models.DateField()),
                ('serie', models.CharField(max_length=30)),
                ('escola', models.TextField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='classroom.Professor')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['id'],
                'unique_together': {('professor',)},
            },
        ),
    ]
