# Generated by Django 2.2.9 on 2020-04-15 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200415_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aluno',
            unique_together=set(),
        ),
    ]
